global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
